execute_process(COMMAND nm -D --defined-only "${LIBRARY}" OUTPUT_VARIABLE symbols RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "nm failed")
endif()
set(expected PassThruOpen PassThruClose PassThruConnect PassThruDisconnect PassThruReadMsgs PassThruWriteMsgs PassThruStartPeriodicMsg PassThruStopPeriodicMsg PassThruStartMsgFilter PassThruStopMsgFilter PassThruSetProgrammingVoltage PassThruReadVersion PassThruGetLastError PassThruIoctl)
foreach(symbol IN LISTS expected)
  if(NOT symbols MATCHES " ${symbol}@@MONGOOSE_0")
    message(FATAL_ERROR "Missing export ${symbol}")
  endif()
endforeach()
string(REGEX MATCHALL " T [^\n]+" functions "${symbols}")
list(LENGTH functions count)
if(NOT count EQUAL 14)
  message(FATAL_ERROR "Expected exactly 14 function exports, found ${count}")
endif()
